### ISSUE TITLE
Installing ijson with yajl_c backend on MacOS

### ISSUE THREAD

**Issue by anton-daneyko-ultramarin** [ICRAR/ijson#129]
I am sorry for hacking the GH Issues for that, but I thought it might be helpful to make it searcheable for someone experiencing the same problems.

I had two issues intalling ijson with conda:
1. On MacOS (Apple Silicon) given the environment.yaml
```
name: my-env
channels:
  - conda-forge
dependencies:
  - ijson ~= 3.3
```
I would get a `python` backend. The way to get the `yajl_c` backend was to use pip:
```
name: my-env
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - ijson ~= 3.3
```

2. On Linux I somehow assumed that I do need to install `yajl` so it could be found by `ijson`, so I started from environment.yml like this:
```
name: my-env
channels:
  - conda-forge
dependencies:
  - ijson ~= 3.3
  - yajl
```
which resulted in `yajl_cffi` backend (which was ~10x slower than `yajl_cffi`). Removing `yajl` from the environment did result in `yajl_c` backend.

**Comment by rtobar** [comment]
@anton-daneyko-ultramarin thanks for your interest in sharing knowledge. I'd prefer issues were reserved for reporting issues rather than for people posting arbitrary troubleshooting guidance though. Since you already created this, could you at least add a bit more of context? I have no idea what this `environment.yaml` files are for, nor why the PyPI binaries don't work for you (they all have built-in support for `yajl2_c` in macOS across x64/arm64).

I haven't published a new version of ijson in a while, so there are binary wheels missing for 3.13. Is this the problem you were facing?

**Comment by rtobar** [comment]
Thanks @anton-daneyko-ultramarin for the further details, it's much appreciated. You're right about Discussions not being available, I've turned them on now, I think it's a good idea to have something different to Issues for people to ask/discuss topics.

> do I get it right that ijson tries to compile yajl during installation?

Only if `IJSON_EMBED_YAJL` is set to 1: https://github.com/ICRAR/ijson/blob/698b114e7cf780f7aedde57fd79d2f10d58b8e26/setup.py#L108
That's set for macOS and Windows wheel builds: https://github.com/ICRAR/ijson/blob/698b114e7cf780f7aedde57fd79d2f10d58b8e26/.github/workflows/deploy-to-pypi.yml#L75-L76

Otherwise ijson tries to find an installed yajl and it links to that. Linux distros build the package that way.

> Would you be interested in a contribution that adds ability to validate JSON against a JSON schema?

I appreciate the interest, but no, not really. It sounds like a big, complex feature that will never be fully finished, and where users will request more and more features, and I'm in no position to add that extra load on me. Having said that, I feel you should be able to implement this separately, bulding it *on top* of ijson, not *in* ijson. Happy to help answering questions!

**Comment by anton-daneyko-ultramarin** [comment]
I've cleared out some more details about why I don't get `yajl_c` backend with Conda. I will leave it here in case someone tries to look into it further.

There are different channels from which the binaries are pulled and in my set up I use `conda-forge` (as in my `environment.yml`). When I use that, the `python` backend is installed. If I use `default` Conda channel, I get `yajl_c`. I have compared the recipes for them and they look different.

The bit of `meta.yaml` from `defaults` channel (from https://anaconda.org/anaconda/ijson/3.3.0/download/osx-arm64/ijson-3.3.0-py312h80987f9_1.tar.bz2):
```
build:
  missing_dso_whitelist: null
  number: '1'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_023qd3dkhk/croot/ijson_1736366668574/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312h80987f9_1
requirements:
  build:
    - cctools_osx-arm64 949.0.1 h332cad3_25
    - clang 14.0.6 hca03da5_2
    - clang-14 14.0.6 default_h1b80db6_2
    - clang_osx-arm64 14.0.6 h9ff6fda_0
    - clangxx 14.0.6 default_h1b80db6_2
    - compiler-rt 14.0.6 h4ccfd99_0
    - compiler-rt_osx-arm64 14.0.6 h4fb70ea_0
    - ld64_osx-arm64 530 h001ce53_25
    - ldid 2.1.5 h20b2a84_3
    - libclang-cpp14 14.0.6 default_h1b80db6_2
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - libllvm14 14.0.6 h19fdd8a_4
    - llvm-tools 14.0.6 h7ec7a93_4
    - tapi 1100.0.11 h8754e6a_1
    - zlib 1.2.13 h18a0788_1
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.12.31 hca03da5_0
    - expat 2.6.4 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - pip 24.2 py312hca03da5_0
    - python 3.12.8 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - yajl 2.1.0 h1a28f6b_1
    - zlib 1.2.13 h18a0788_1
  run:
    - python >=3.12,<3.13.0a0
    - yajl >=2.1.0,<3.0.0
```
The bit of `meta.yaml` from `conda-forge` channel (from https://github.com/conda-forge/ijson-feedstock/blob/main/recipe/meta.yaml): 
```
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
```

So it is possible to install `ijson` with Conda using:
```
name: my-env
channels:
  - default
dependencies:
  - python ~= 3.12.0
  - ijson ~= 3.3
```

Also, I've noticed that `yajl` on `conda-forge` does not have osx-arm64 build.
